# Generated by Django 3.2.16 on 2023-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otherproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrfppartno', models.TextField(blank=True, db_column='MrfpPartNo', null=True)),
                ('datasheet', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('mounting_type', models.TextField(blank=True, db_column='Mounting Type', null=True)),
            ],
            options={
                'db_table': 'OtherProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surfaceproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrfppartno', models.TextField(blank=True, db_column='MrfpPartNo', null=True)),
                ('datasheet', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('mounting_type', models.TextField(blank=True, db_column='Mounting Type', null=True)),
            ],
            options={
                'db_table': 'SurfaceProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Throughproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrfppartno', models.TextField(blank=True, db_column='MrfpPartNo', null=True)),
                ('datasheet', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('mounting_type', models.TextField(blank=True, db_column='Mounting Type', null=True)),
            ],
            options={
                'db_table': 'ThroughProducts',
                'managed': False,
            },
        ),
    ]
